# Generated by Django 3.1.4 on 2020-12-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='userName',
            new_name='username',
        ),
    ]
